import { createFileRoute } from "@tanstack/react-router";
import { AppWindow, ArrowRight, Box, Check, ChevronDown, Clock3, Heart, Home, Leaf, MonitorSmartphone, PawPrint, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/")({ component: Index });
const photos=["https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=900&q=82","https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=900&q=82","https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=82","https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=900&q=82","https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=900&q=82","https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=900&q=82","https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?auto=format&fit=crop&w=900&q=82"];
const instincts=[["Caçar","🎯"],["Explorar","🔎"],["Escalar","🧗"],["Esconder-se","📦"],["Arranhar","🐾"],["Procurar alimento","🥣"],["Criar vínculo","💛"]];
const missions=[["Caixa Surpresa","Explorar","5 min"],["Caça ao Tesouro","Procurar alimento","4 min"],["Cidade de Papelão","Esconder-se","12 min"],["Observatório Felino","Explorar","7 min"],["Túnel Mutante","Caçar","8 min"],["Caminho das Texturas","Explorar","6 min"]];
const faqs=[["Preciso comprar materiais?","Não. A proposta é usar objetos comuns que você provavelmente já tem, como caixas, papel, toalhas e móveis."],["É um aplicativo? Preciso instalar?","É um aplicativo online, acessado por um link. Você não precisa baixar nem instalar nada: basta abrir no navegador."],["Posso acessar em qualquer dispositivo?","Sim. O aplicativo é totalmente responsivo e funciona no celular, computador ou tablet."],["Funciona em apartamento pequeno?","Sim. Você encontra filtros e adaptações específicas para pouco espaço em cada missão."],["Meu gato é idoso. Ele pode participar?","Há missões por idade, energia e mobilidade. Respeite sempre os limites do seu gato e, em caso de condição de saúde, consulte o veterinário."],["Como recebo o acesso?","Após a confirmação da compra, você recebe o link para entrar no aplicativo online e começar imediatamente."],["Substitui acompanhamento veterinário?","Não. Missão Felina é um material educativo de enriquecimento e interação, não substitui avaliação ou tratamento veterinário."]];

function CatYarn(){return <div className="cat-stage" aria-label="Gato animado brincando com um novelo"><i className="spark s1">✦</i><i className="spark s2">✦</i><svg viewBox="0 0 520 360" role="img"><path className="tail" d="M322 253c74 43 134 15 121-33-8-29-48-29-58-4"/><ellipse className="body" cx="290" cy="222" rx="89" ry="77"/><path className="ear" d="M199 121l-6-73 62 52zM286 99l48-53 8 82z"/><path className="inner" d="M209 101l-5-37 31 28zM305 92l24-29 3 42z"/><ellipse className="head" cx="267" cy="137" rx="78" ry="67"/><path className="face" d="M228 135q14 12 28-1m32 0q14 12 28-2m-48 19l9 1-5 7m0 0q-4 12-14 5m14-5q5 11 15 4"/><path className="whisker" d="M236 158l-58-7m61 18l-58 12m126-22l54-13m-52 25l57 6"/><path className="paw p1" d="M233 228q-32 26-42 72"/><path className="paw p2" d="M274 236q-18 45-40 71"/><path className="thread" d="M225 304c45-1 57-28 25-42-26-12-41 22-14 35 42 20 94-6 106 30"/><g className="yarn"><circle cx="365" cy="325" r="31"/><path d="M345 306c25 7 39 23 42 36m-46-16c17-12 34-17 53-11m-42 31c4-19 17-34 36-43"/></g></svg><div className="stage-note"><PawPrint/> Uma nova aventura começa com o que você já tem</div></div>}
function FAQ({q,a}:{q:string;a:string}){const[open,setOpen]=useState(false);return <div className={`faq-item ${open?"open":""}`}><button onClick={()=>setOpen(!open)} aria-expanded={open}>{q}<ChevronDown/></button><div><p>{a}</p></div></div>}
function CTA({children="QUERO COMEÇAR AS MISSÕES"}:{children?:string}){return <a className="cta" href="#ofertas">{children}<ArrowRight/></a>}

function Index(){return <main>
  <div className="topbar">🐾 Seu gato não precisa sair de casa para viver novas aventuras.</div>
  <header className="nav shell"><a href="#inicio" className="brand"><span><PawPrint/></span>Missão <b>Felina</b></a><a href="#ofertas" className="nav-cta">Ver as missões</a></header>
  <section className="hero" id="inicio"><div className="shell hero-grid"><div><div className="eyebrow"><Sparkles/>100 experiências dentro de casa</div><h1>Transforme objetos comuns em <em>aventuras inesquecíveis</em> para o seu gato.</h1><p className="lead">Ative os instintos naturais do seu gato com missões rápidas, seguras e divertidas — sem reformas e sem gastar com brinquedos caros.</p><div className="pills"><span><Clock3/>Poucos minutos</span><span><Home/>Qualquer espaço</span><span><Box/>Materiais que você já tem</span></div><CTA/><small className="micro"><MonitorSmartphone/>Aplicativo online • Celular, computador ou tablet • Não precisa instalar</small></div><CatYarn/></div></section>
  <section className="app-strip"><div className="shell"><AppWindow/><div><b>Não é e-book. É um aplicativo online interativo.</b><span>Você recebe o link, abre no navegador e começa. Sem download, sem instalação e em qualquer dispositivo.</span></div><div className="device-dots"><i>CELULAR</i><i>TABLET</i><i>COMPUTADOR</i></div></div></section>
  <section className="section"><div className="shell split"><figure className="scene"><img src={photos[1]} alt="Gato curioso dentro de uma caixa de papelão" loading="lazy"/><div className="tag">R$ 89</div><figcaption>O brinquedo caro ficou de lado.<br/><b>A caixa venceu de novo.</b></figcaption></figure><div className="copy"><span className="kicker">Existe um motivo para isso</span><h2>O que prende a atenção não é o preço. É a <em>experiência.</em></h2><p>Gatos são movidos por oportunidades de caçar, investigar, esconder-se, escalar e descobrir algo novo. Por isso, um objeto simples pode ser muito mais interessante que um brinquedo que faz sempre a mesma coisa.</p><p className="highlight"><Heart/>Com a Missão Felina, você aprende a renovar o território dele com criatividade, carinho e segurança.</p></div></div></section>
  <section className="section method"><div className="shell center"><span className="kicker light">O mecanismo por trás das missões</span><h2>O Método dos <em>7 Instintos</em></h2><p className="intro">Em vez de uma lista aleatória, cada atividade desperta comportamentos que fazem parte da natureza felina.</p><div className="instincts">{instincts.map(([n,i],x)=><div key={n}><img src={photos[x]} alt={"Gato representando o instinto de "+n.toLowerCase()} loading="lazy"/><i>{i}</i><span>0{x+1}</span><b>{n}</b></div>)}</div><blockquote>“Uma atividade continua interessante quando oferece novas maneiras de investigar, escolher e descobrir.”</blockquote></div></section>
  <section className="section"><div className="shell center"><span className="kicker">Abra uma carta. Comece uma aventura.</span><h2>Conheça algumas das <em>100 missões</em></h2><p className="intro dark">Cada carta mostra materiais, tempo, dificuldade, energia, passo a passo, variações e cuidados.</p><div className="missions">{missions.map(([t,k,time],i)=><article key={t}><header><span>MISSÃO {String(i+1).padStart(2,"0")}</span><PawPrint/></header><div className="mission-photo"><img src={photos[(i+1)%photos.length]} alt={"Exemplo visual da missão "+t} loading="lazy"/></div><h3>{t}</h3><div className="meta"><span>{k}</span><span><Clock3/>{time}</span></div><footer>Materiais simples • Passo a passo</footer></article>)}</div><p className="more"><Sparkles/>E mais 94 aventuras para renovar a rotina sem cair na mesmice.</p></div></section>
  <section className="section how"><div className="shell"><div className="center"><span className="kicker">Do “salvei para depois” ao “vamos brincar”</span><h2>Encontre a missão certa <em>em segundos</em></h2><p className="intro dark">O painel cruza o perfil do seu gato com o tempo, o espaço e os materiais que você tem.</p></div><div className="finder"><div><div className="app-window"><span></span><span></span><span></span><b>Missão Felina • Gerador</b></div><h3>Você olha o que tem em casa.<br/>O aplicativo mostra o que criar.</h3><ul><li><Box/>Tenho uma caixa de papelão</li><li>🧻 Tenho rolos de papel</li><li>🛋️ Tenho pouco espaço</li><li><Clock3/>Tenho apenas cinco minutos</li></ul></div><aside><small>MISSÕES ENCONTRADAS</small><b>12</b><p>aventuras com caixa de papelão</p><span>📦 Caixa Surpresa</span><span>🏘️ Cidade de Papelão</span><span>🌀 Túnel Mutante</span><button>Sortear uma missão <ArrowRight/></button></aside></div><div className="works-anywhere"><MonitorSmartphone/><b>Funciona onde você estiver.</b><span>Abra no celular, tablet ou computador — sem instalar nada.</span></div></div></section>
  <section className="section"><div className="shell split"><div className="kit"><img className="kit-photo" src={photos[5]} alt="Gato aproveitando uma experiência dentro de casa" loading="lazy"/><div className="calendar"><small>30 DIAS DE</small><b>AVENTURAS</b><section>{Array.from({length:12}).map((_,i)=><span className={i<7?"done":""} key={i}>{i<7?<Check/>:i+1}</span>)}</section></div><div className="phone"><small>MISSÃO DO DIA</small><div>🎯</div><b>Caça Noturna</b><span>8 min • Energia média</span></div></div><div className="copy"><span className="kicker">Seu aplicativo de aventuras felinas</span><h2>Um sistema simples para criar <em>novidades todos os dias</em></h2><p>Escolha, filtre ou sorteie uma experiência. Tudo organizado em um aplicativo online bonito, rápido e fácil de usar.</p><ul className="checklist"><li><Check/>Aplicativo online com 100 missões</li><li><Check/>Calendário “30 Dias de Aventuras”</li><li><Check/>Gerador de atividades por perfil</li><li><Check/>Filtros por idade, energia, espaço e tempo</li><li><Check/>Diário de preferências do seu gato</li><li><Check/>Qualquer dispositivo, sem instalação</li></ul></div></div></section>
  <section className="section benefits"><div className="shell center"><span className="kicker light">Uma casa mais interessante. Uma rotina mais próxima.</span><h2>Bom para o gato. <em>Leve para você.</em></h2><div className="benefit-grid">{[[Zap,"Rápido","Poucos minutos para preparar."],[Leaf,"Econômico","Use materiais simples da casa."],[Home,"Adaptável","Para apartamentos e espaços pequenos."],[Heart,"Afetivo","Interação respeitando as escolhas dele."]].map(([I,t,p]:any)=><div key={t}><I/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
  <section className="section offers" id="ofertas"><div className="shell center"><span className="kicker">Escolha como começar</span><h2>Qual será a próxima <em>missão?</em></h2><p className="intro dark">Você recebe o acesso ao aplicativo online e pode começar pelo dispositivo que preferir.</p><div className="offer-grid"><Offer small/><Offer/></div><div className="secure"><ShieldCheck/>Compra segura • Acesso pelo navegador • Nenhuma instalação</div></div></section>
  <section className="section guarantee"><div className="shell"><div className="guarantee-seal"><ShieldCheck/><b>GARANTIA</b><span>SATISFAÇÃO</span></div><div><span className="kicker light">Sua compra está protegida</span><h2>Compre com garantia total de satisfação.</h2><p>Você pode começar hoje a criar um lar mais acolhedor e interessante para o seu gatinho sem correr riscos.</p><p>Acesse o aplicativo, conheça as atividades e explore as possibilidades. Caso perceba que o conteúdo não faz sentido para a sua rotina, você poderá solicitar o reembolso dentro de 7 dias. Após a aprovação, a devolução será processada pelo mesmo meio de pagamento utilizado na compra.</p><strong>Você experimenta. Seu gato explora. E a sua compra continua protegida.</strong><small>Garantia de satisfação de <b>7 dias</b>.</small></div></div></section>
  <section className="section safety"><div className="shell"><ShieldCheck/><div><span className="kicker">Diversão responsável</span><h2>A segurança vem antes de cada missão.</h2><p>As atividades incluem orientações de supervisão, materiais a evitar, adaptações e respeito à idade, mobilidade e vontade do gato. Petiscos devem ser considerados na alimentação diária.</p><small>Conteúdo educativo. Não substitui acompanhamento veterinário.</small></div></div></section>
  <section className="section faq"><div className="shell"><div><span className="kicker">Dúvidas frequentes</span><h2>Antes de começar a aventura…</h2><p>Veja as respostas para as perguntas mais comuns.</p></div><div>{faqs.map(([q,a])=><FAQ key={q} q={q} a={a}/>)}</div></div></section>
  <section className="final"><div className="shell"><PawPrint/><h2>100 aventuras para seu gato explorar o mundo<br/><em>sem precisar sair de casa.</em></h2><p>Escolha uma missão, prepare em poucos minutos e descubra o que faz os olhos dele brilharem.</p><CTA>QUERO COMEÇAR AGORA</CTA><div>★★★★★ <span>feito para quem ama gatos</span></div></div></section>
  <footer className="site-footer"><div className="shell"><div className="brand"><span><PawPrint/></span>Missão <b>Felina</b></div><p>© 2026 Missão Felina. Todos os direitos reservados.</p><p>Material educativo de enriquecimento ambiental.</p></div></footer>
</main>}

function Offer({small=false}:{small?:boolean}){const items=small?["Acesso ao aplicativo online","20 atividades ilustradas","Calendário de 7 dias","Use em qualquer dispositivo","Não precisa instalar"]:["Acesso completo ao aplicativo","100 atividades ilustradas","Método dos 7 Instintos","Calendário de 30 dias","Gerador por perfil","Filtros por idade, energia e espaço","Diário de preferências","Atualizações futuras"];return <article className={`offer ${small?"":"featured"}`}>{!small&&<div className="best">MAIS ESCOLHIDO</div>}<img className="offer-photo" src={small?photos[3]:photos[0]} alt={`Aplicativo com ${small?20:100} missões felinas`} loading="lazy"/><small>{small?"PRIMEIROS PASSOS":"EXPERIÊNCIA COMPLETA"}</small><h3>{small?"20":"100"} Missões Felinas</h3><p>{small?"Para experimentar uma nova rotina com seu gato.":"Tudo para nunca faltar uma nova aventura."}</p><div className="price"><i>R$</i><b>{small?"9,90":"19,90"}</b></div>{!small&&<div className="value-note">5x mais atividades por apenas R$ 10 a mais</div>}<ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><a href="#" className="buy">QUERO {small?"20":"AS 100"} MISSÕES</a><span>Acesso imediato pelo navegador</span></article>}
