import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Box, Check, ChevronDown, Clock3, Heart, Home, Leaf, MonitorSmartphone, PawPrint, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/")({ component: Index });
const instinctImages=["/assets/instinct-hunt.webp","/assets/instinct-explore.webp","/assets/instinct-climb.webp","/assets/instinct-hide.webp","/assets/instinct-scratch.webp","/assets/instinct-food.webp","/assets/instinct-bond.webp"];
const missionImages=["/assets/mission-surprise-box.webp","/assets/mission-treasure-hunt.webp","/assets/mission-cardboard-city.webp","/assets/mission-window-adventure.webp","/assets/mission-cushion-tunnel.webp","/assets/mission-texture-path.webp"];
const instincts=[["Caçar","🎯"],["Explorar","🔎"],["Escalar","🧗"],["Esconder-se","📦"],["Arranhar","🐾"],["Procurar alimento","🥣"],["Criar vínculo","💛"]];
const missions=[["Caixa Surpresa","Explorar","5 min"],["Caça ao Tesouro","Procurar alimento","4 min"],["Cidade de Papelão","Esconder-se","12 min"],["Janela de Aventuras","Explorar","3 min"],["Túnel de Almofadas","Caçar","4 min"],["Caminho das Texturas","Explorar","6 min"]];
const faqs=[["Preciso comprar materiais?","Não. A proposta é usar objetos comuns que você provavelmente já tem, como caixas, papel, toalhas e móveis."],["É um aplicativo? Preciso instalar?","É um aplicativo online, acessado por um link. Você não precisa baixar nem instalar nada: basta abrir no navegador."],["Posso acessar em qualquer dispositivo?","Sim. O aplicativo é totalmente responsivo e funciona no celular, computador ou tablet."],["Funciona em apartamento pequeno?","Sim. Você encontra filtros e adaptações específicas para pouco espaço em cada missão."],["Meu gato é idoso. Ele pode participar?","Há missões por idade, energia e mobilidade. Respeite sempre os limites do seu gato e, em caso de condição de saúde, consulte o veterinário."],["Como recebo o acesso?","Após a confirmação da compra, você recebe o link para entrar no aplicativo online e começar imediatamente."],["Substitui acompanhamento veterinário?","Não. Missão Felina é um material educativo de enriquecimento e interação, não substitui avaliação ou tratamento veterinário."]];

function CatYarn(){return <div className="cat-stage" aria-label="Gato animado brincando com um novelo"><i className="spark s1">✦</i><i className="spark s2">✦</i><svg viewBox="0 0 520 360" role="img"><path className="tail" d="M322 253c74 43 134 15 121-33-8-29-48-29-58-4"/><ellipse className="body" cx="290" cy="222" rx="89" ry="77"/><path className="ear" d="M199 121l-6-73 62 52zM286 99l48-53 8 82z"/><path className="inner" d="M209 101l-5-37 31 28zM305 92l24-29 3 42z"/><ellipse className="head" cx="267" cy="137" rx="78" ry="67"/><path className="face" d="M228 135q14 12 28-1m32 0q14 12 28-2m-48 19l9 1-5 7m0 0q-4 12-14 5m14-5q5 11 15 4"/><path className="whisker" d="M236 158l-58-7m61 18l-58 12m126-22l54-13m-52 25l57 6"/><path className="paw p1" d="M233 228q-32 26-42 72"/><path className="paw p2" d="M274 236q-18 45-40 71"/><path className="thread" d="M225 304c45-1 57-28 25-42-26-12-41 22-14 35 42 20 94-6 106 30"/><g className="yarn"><circle cx="365" cy="325" r="31"/><path d="M345 306c25 7 39 23 42 36m-46-16c17-12 34-17 53-11m-42 31c4-19 17-34 36-43"/></g></svg><div className="stage-note"><PawPrint/> Uma nova aventura começa com o que você já tem</div></div>}
function FAQ({q,a}:{q:string;a:string}){const[open,setOpen]=useState(false);return <div className={`faq-item ${open?"open":""}`}><button onClick={()=>setOpen(!open)} aria-expanded={open}>{q}<ChevronDown/></button><div><p>{a}</p></div></div>}
function CTA({children="QUERO COMEÇAR AS MISSÕES"}:{children?:string}){return <a className="cta" href="#ofertas">{children}<ArrowRight/></a>}

function Index(){return <main>
  <header className="nav shell"><a href="#inicio" className="brand"><span><PawPrint/></span>Missão <b>Felina</b></a><a href="#ofertas" className="nav-cta">Ver as missões</a></header>
  <section className="hero" id="inicio"><div className="shell hero-grid"><div><div className="eyebrow"><Sparkles/>Um recado urgente do seu gato</div><h1>Ei, humano… que tal vivermos <em>100 aventuras juntos?</em></h1><p className="lead">Eu adoro dormir, mas também preciso caçar, explorar, escalar e descobrir coisas novas. Transforme o que você já tem em casa em missões rápidas, seguras e muito divertidas para nós dois.</p><div className="pills"><span><Clock3/>Poucos minutos</span><span><Home/>Qualquer espaço</span><span><Box/>Materiais que você já tem</span></div><CTA>SIM, MEU GATO MANDOU</CTA><small className="micro"><MonitorSmartphone/>Aplicativo online • Celular, computador ou tablet • Não precisa instalar</small></div><figure className="hero-meme"><div className="speech">“Prometo tentar não derrubar nada… se você brincar comigo.”</div><img src="https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aWlqY29iNTN2dTUxZTByM2N6M2QzbjZsbGVmZXU4ODc4ZWo0MnplYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/TbRkubcqlgBksEqMv4/giphy.gif" alt="Gato fazendo uma expressão engraçada e chamando seu humano para brincar"/><figcaption><PawPrint/>Seu novo supervisor de aventuras</figcaption></figure></div></section>
  <section className="section"><div className="shell split"><figure className="scene"><img src="/assets/experience-box.webp" alt="Gato feliz dentro de uma caixa enquanto ignora um brinquedo caro" loading="lazy"/><div className="tag">R$ 89</div><figcaption>Você comprou o brinquedo caro.<br/><b>Eu escolhi a caixa. Foi mal, humano.</b></figcaption></figure><div className="copy"><span className="kicker">Deixa eu te explicar uma coisa</span><h2>O que prende minha atenção não é o preço. É a <em>experiência.</em></h2><p>Eu sou movido por oportunidades de caçar, investigar, esconder, escalar e descobrir algo novo. Por isso, uma caixa simples pode ser muito mais interessante do que um brinquedo que faz sempre a mesma coisa.</p><p className="highlight"><Heart/>Com a Missão Felina, você renova meu território com criatividade, carinho e segurança — e eu finalmente paro de olhar para você como se estivesse devendo diversão.</p></div></div></section>
  <section className="section method"><div className="shell center"><span className="kicker light">Não é bagunça. É instinto.</span><h2>Os meus <em>7 Instintos</em></h2><p className="intro">Cada missão desperta um comportamento que já faz parte de mim. Você chama de brincadeira. Eu chamo de treinamento felino avançado.</p><div className="instincts">{instincts.map(([n],x)=><div key={n}><img src={instinctImages[x]} alt={"Gato representando o instinto de "+n.toLowerCase()} loading="lazy"/><span>0{x+1}</span><b>{n}</b></div>)}</div><blockquote>“Se eu posso investigar, escolher e descobrir, quero brincar de novo.” — seu gato, provavelmente</blockquote></div></section>
  <section className="section"><div className="shell center"><span className="kicker">Abra uma carta. Comece uma aventura.</span><h2>Conheça algumas das <em>100 missões</em></h2><p className="intro dark">Cada carta mostra materiais, tempo, dificuldade, energia, passo a passo, variações e cuidados.</p><div className="missions">{missions.map(([t,k,time],i)=><article key={t}><header><span>MISSÃO {String(i+1).padStart(2,"0")}</span><PawPrint/></header><div className="mission-photo"><img src={missionImages[i]} alt={"Exemplo visual da missão "+t} loading="lazy"/></div><h3>{t}</h3><div className="meta"><span>{k}</span><span><Clock3/>{time}</span></div><footer>Materiais simples • Passo a passo</footer></article>)}</div><p className="more"><Sparkles/>E mais 94 aventuras para renovar a rotina sem cair na mesmice.</p></div></section>
  <section className="section how"><div className="shell"><div className="center"><span className="kicker">Do “salvei para depois” ao “vamos brincar”</span><h2>Encontre a missão certa <em>em segundos</em></h2><p className="intro dark">O aplicativo cruza o perfil do seu gato com o tempo, o espaço e os materiais que você tem.</p></div><div className="finder finder-mockup"><div><h3>Você olha o que tem em casa.<br/>O aplicativo mostra o que criar.</h3><ul><li><Box/>Tenho uma caixa de papelão</li><li>🧻 Tenho rolos de papel</li><li>🛋️ Tenho pouco espaço</li><li><Clock3/>Tenho apenas cinco minutos</li></ul><p>O resultado aparece com as missões mais adequadas ao perfil, à energia e à rotina do seu gato.</p></div><figure><img src="/assets/app-phone-mockup.webp" alt="Aplicativo Missão Felina aberto no celular mostrando doze missões encontradas" loading="lazy"/></figure></div><div className="works-anywhere"><MonitorSmartphone/><b>Funciona onde você estiver.</b><span>Abra no celular, tablet ou computador — sem instalar nada.</span></div></div></section>
  <section className="section"><div className="shell split"><figure className="system-visual"><img src="/assets/daily-adventures-app.webp" alt="Gato vivendo uma aventura com o aplicativo Missão Felina aberto no celular e tablet" loading="lazy"/></figure><div className="copy"><span className="kicker">Seu aplicativo de aventuras felinas</span><h2>Um sistema simples para criar <em>novidades todos os dias</em></h2><p>Escolha, filtre ou sorteie uma experiência. Tudo organizado em um aplicativo online bonito, rápido e fácil de usar.</p><ul className="checklist"><li><Check/>Aplicativo online com 100 missões</li><li><Check/>Calendário “30 Dias de Aventuras”</li><li><Check/>Gerador de atividades por perfil</li><li><Check/>Filtros por idade, energia, espaço e tempo</li><li><Check/>Diário de preferências do seu gato</li><li><Check/>Qualquer dispositivo, sem instalação</li></ul></div></div></section>
  <section className="section benefits"><div className="shell center"><span className="kicker light">Uma casa mais interessante. Uma rotina mais próxima.</span><h2>Bom para o gato. <em>Leve para você.</em></h2><div className="benefit-grid">{[[Zap,"Rápido","Poucos minutos para preparar."],[Leaf,"Econômico","Use materiais simples da casa."],[Home,"Adaptável","Para apartamentos e espaços pequenos."],[Heart,"Afetivo","Interação respeitando as escolhas dele."]].map(([I,t,p]:any)=><div key={t}><I/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
  <section className="section offers" id="ofertas"><div className="shell center"><span className="kicker">Escolha como começar</span><h2>Qual será a próxima <em>missão?</em></h2><p className="intro dark">Você recebe o acesso ao aplicativo online e pode começar pelo dispositivo que preferir.</p><div className="offer-grid"><Offer small/><Offer/></div><div className="secure"><ShieldCheck/>Compra segura • Acesso pelo navegador • Nenhuma instalação</div></div></section>
  <section className="section cat-health"><div className="shell"><div className="health-intro"><figure><img src="https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aWlqY29iNTN2dTUxZTByM2N6M2QzbjZsbGVmZXU4ODc4ZWo0MnplYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/TbRkubcqlgBksEqMv4/giphy.gif" alt="Gato assustado ao descobrir que também precisa se exercitar" loading="lazy"/><figcaption>“COMO ASSIM EU TAMBÉM PRECISO ME EXERCITAR?”</figcaption></figure><div><span className="kicker">Calma, não precisa de academia felina</span><h2>Sim, humano: eu também preciso <em>me movimentar.</em></h2><p>Brincar e explorar ajudam a oferecer oportunidades de movimento, desafio mental e expressão de comportamentos naturais. A falta de exercício, especialmente junto com excesso de alimento, pode contribuir para ganho de peso.</p><p>Isso não significa que toda bagunça seja “tédio” — mas um ambiente com esconderijos, superfícies para arranhar, pontos altos e brincadeiras dá ao gato opções mais adequadas para gastar energia.</p></div></div><div className="cat-compare"><article className="without"><span>😾 Sem oportunidades de atividade</span><h3>Modo: “vou inventar meu próprio entretenimento”</h3><ul><li>Menos oportunidades de movimento</li><li>Rotina mais previsível e pouco desafiadora</li><li>Energia sem uma saída apropriada</li><li>Maior dificuldade para controlar o peso quando há excesso de calorias</li></ul></article><article className="with"><span>😸 Com uma rotina de aventuras</span><h3>Modo: explorador profissional da casa</h3><ul><li>Mais oportunidades de brincar e se movimentar</li><li>Estímulo aos comportamentos naturais</li><li>Novidades sem precisar sair de casa</li><li>Mais momentos positivos entre gato e tutor</li></ul></article></div><p className="health-note"><ShieldCheck/>Cada gato tem idade, mobilidade e condições próprias. Mudanças de peso ou comportamento devem ser avaliadas por um médico-veterinário.</p></div></section>
  <section className="section guarantee"><div className="shell"><figure className="vet-visual"><img src="/assets/guarantee-vet-v2.webp" alt="Médica veterinária realista sorrindo, dando joinha e aprovando ao lado de um gato" loading="lazy"/><div className="gold-seal"><ShieldCheck/><b>7 DIAS</b><span>GARANTIA</span></div></figure><div><span className="kicker light">Sua compra está protegida</span><h2>Compre com garantia total de satisfação.</h2><p>Você pode começar hoje a criar um lar mais acolhedor e interessante para o seu gatinho sem correr riscos.</p><p>Acesse o aplicativo, conheça as atividades e explore as possibilidades. Caso perceba que o conteúdo não faz sentido para a sua rotina, você poderá solicitar o reembolso dentro de 7 dias. Após a aprovação, a devolução será processada pelo mesmo meio de pagamento utilizado na compra.</p><strong>Você experimenta. Seu gato explora. E a sua compra continua protegida.</strong><small>Garantia de satisfação de <b>7 dias</b>.</small></div></div></section>
  <section className="section faq"><div className="shell"><div><span className="kicker">Dúvidas frequentes</span><h2>Antes de começar a aventura…</h2><p>Veja as respostas para as perguntas mais comuns.</p></div><div>{faqs.map(([q,a])=><FAQ key={q} q={q} a={a}/>)}</div></div></section>
  <section className="final"><div className="shell"><PawPrint/><h2>100 aventuras para seu gato explorar o mundo<br/><em>sem precisar sair de casa.</em></h2><p>Escolha uma missão, prepare em poucos minutos e descubra o que faz os olhos dele brilharem.</p><CTA>QUERO COMEÇAR AGORA</CTA><div>★★★★★ <span>feito para quem ama gatos</span></div></div></section>
  <footer className="site-footer"><div className="shell"><div className="brand"><span><PawPrint/></span>Missão <b>Felina</b></div><p>© 2026 Missão Felina. Todos os direitos reservados.</p><p>Material educativo de enriquecimento ambiental.</p></div></footer>
</main>}

function Offer({small=false}:{small?:boolean}){const items=small?["Acesso ao aplicativo online","20 atividades ilustradas","Calendário de 7 dias","Use em qualquer dispositivo","Não precisa instalar"]:["Acesso completo ao aplicativo","100 atividades ilustradas","Método dos 7 Instintos","Calendário de 30 dias","Gerador por perfil","Filtros por idade, energia e espaço","Diário de preferências","Atualizações futuras"];return <article className={`offer ${small?"":"featured"}`}>{!small&&<div className="best">MAIS ESCOLHIDO</div>}<img className="offer-photo" src={small?"/assets/offer-basic.webp":"/assets/offer-complete.webp"} alt={`Universo visual do aplicativo com ${small?20:100} missões felinas`} loading="lazy"/><small>{small?"PRIMEIROS PASSOS":"EXPERIÊNCIA COMPLETA"}</small><h3>{small?"20":"100"} Missões Felinas</h3><p>{small?"Para experimentar uma nova rotina com seu gato.":"Tudo para nunca faltar uma nova aventura."}</p><div className="price"><i>R$</i><b>{small?"9,90":"19,90"}</b></div>{!small&&<div className="value-note">5x mais atividades por apenas R$ 10 a mais</div>}<ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><a href="#" className="buy">QUERO {small?"20":"AS 100"} MISSÕES</a><span>Acesso imediato pelo navegador</span></article>}
